WebBanQuanAo/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanQuanAo.Models;

namespace WebBanQuanAo.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        BanQuanAoEntities2 db = new BanQuanAoEntities2();
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(tendn))
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            else if(String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                KhachHang kh = db.KhachHangs.SingleOrDefault(n=>n.TaiKhoan==tendn && n.MatKhau==matkhau);
                if (kh != null)
                {
                    Session["KhachHang"] = kh;
                    return RedirectToAction("Index","Home");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var tenkh = collection["TenKH"];
            var diachi = collection["DiaChi"];
            var email = collection["Email"];
            var sdt = collection["SDT"];
            var taikhoan = collection["TaiKhoan"];
            var matkhau = collection["MatKhau"];
            var xnmatkhau = collection["xnMatKhau"];
            if (String.IsNullOrEmpty(tenkh))
                ViewBag.Thongbao = "Tên không được để trống";
            else if (String.IsNullOrEmpty(diachi))
                ViewBag.Thongbao = "Địa chỉ không được để trống";
            else if (String.IsNullOrEmpty(email))
                ViewBag.Thongbao = "Email không được để trống";
            else if (String.IsNullOrEmpty(sdt))
                ViewBag.Thongbao = "Số điện thoại không được để trống";
            else if (String.IsNullOrEmpty(taikhoan))
                ViewBag.Thongbao = "Tài khoản không được để trống";
            else if (String.IsNullOrEmpty(matkhau))
                ViewBag.Thongbao = "Mật khẩu không được để trống";
            else if (String.IsNullOrEmpty(xnmatkhau))
                ViewBag.Thongbao = "Xác nhận mật khẩu không được để trống";
            else if(String.Compare(matkhau,xnmatkhau)!=0)
                ViewBag.Thongbao = "Xác nhận mật khẩu không đúng";
            else
            {
                kh.TenKhachHang = tenkh;
                kh.DiaChi = diachi;
                kh.Email = email;
                kh.SoDienThoai = sdt;
                kh.TaiKhoan = taikhoan;
                kh.MatKhau = matkhau;
                db.KhachHangs.Add(kh);
                db.SaveChanges();
                return RedirectToAction("DKTC");
            }
            return this.DangKy();
        }
        public ActionResult DKTC()
        {
            return View();
        }
    }
}

WebBanQuanAo/Views/NguoiDung/DKTC.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DKTC</title>
</head>
<body>
    <div> 
        <h1 style="text-align:center">Chúc mừng bạn đăng ký thành công!</h1>
        <a style="text-align:center; font-size:20px" href="@Url.Action("Index","Home")">Về trang chủ</a>
    </div>
</body>
</html>

WebBanQuanAo/Views/NguoiDung/DangKy.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>
    
    <!-- Icons font CSS-->
    <link href="~/Content/Regin/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/Content/Regin/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="~/Content/Regin/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Content/Regin/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Content/Regin/css/main.css" rel="stylesheet" media="all">
</head>

<body>
    <h1>@ViewBag.Thongbao</h1>
    @using (Html.BeginForm("DangKy", "NguoiDung", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
            <div class="wrapper wrapper--w780">
                <div class="card card-3">
                    <div class="card-heading"></div>
                    <div class="card-body">
                        <h2 class="title">Registration Info</h2>
                        <form>
                            <div class="input-group">
                                <input class="input--style-3" type="text" placeholder="Tên" name="TenKH">
                            </div>
                            <div class="input-group">
                                <input class="input--style-3" type="text" placeholder="Địa chỉ" name="DiaChi">

                            </div>
                            <div class="input-group">
                                <input class="input--style-3" type="email" placeholder="Email" name="Email">

                            </div>
                            <div class="input-group">
                                <input class="input--style-3" type="number" placeholder="Số điện thoại" name="SDT">
                            </div>
                            <div class="input-group">
                                <input class="input--style-3" type="text" placeholder="Tài khoản" name="TaiKhoan">
                            </div>
                            <div class="input-group">
                                <input class="input--style-3" type="password" placeholder="Mật khẩu" name="MatKhau">
                            </div>
                            <div class="input-group">
                                <input class="input--style-3" type="text" placeholder="Xác nhận mật khẩu" name="xnMatKhau">
                            </div>
                            <div class="p-t-10">
                                <button class="btn btn--pill btn--green" type="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
    <!-- Jquery JS-->
    <script src="~/Content/Regin/vendor/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="~/Content/Regin/vendor/select2/select2.min.js"></script>
    <script src="~/Content/Regin/vendor/datepicker/moment.min.js"></script>
    <script src="~/Content/Regin/vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="~/Content/Regin/js/global.js"></script>

</body>

</html>

WebBanQuanAo/Views/NguoiDung/DangNhap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">

    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animsition/css/animsition.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/vendor/daterangepicker/daterangepicker.css">

    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
</head>
<body>
    <h1>@ViewBag.Thongbao</h1>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-t-50 p-b-90">
                @using (Html.BeginForm("DangNhap", "NguoiDung", FormMethod.Post))
                {
                    @Html.ValidationSummary(true)
                    <form class="login100-form validate-form flex-sb flex-w">
                        <span class="login100-form-title p-b-51">
                            Login
                        </span>
                        <div class="wrap-input100 validate-input m-b-16" data-validate="Username is required">
                            <input class="input100" type="text" name="TenDN" placeholder="Username">
                            <span class="focus-input100"></span>
                        </div>


                        <div class="wrap-input100 validate-input m-b-16" data-validate="Password is required">
                            <input class="input100" type="password" name="MatKhau" placeholder="Password">
                            <span class="focus-input100"></span>
                        </div>

                        <div class="flex-sb-m w-full p-t-3 p-b-24">
                            <div class="contact100-form-checkbox">
                                <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                                <label class="label-checkbox100" for="ckb1">
                                    Remember me
                                </label>
                            </div>

                            <div>
                                <a href="#" class="txt1">
                                    Forgot?
                                </a>
                            </div>
                        </div>

                        <div class="container-login100-form-btn m-t-17">
                            <button id="login-btn" class="login100-form-btn" type="submit">
                                Login
                            </button>
                        </div>

                    </form>
                }
                <div style="text-align:center; font-size:19px"> Chưa có tài khoản? <a href="@Url.Action("DangKy","NguoiDung")">Đăng ký ngay!</a></div>
            </div>
        </div>
    </div>


    <div id="dropDownSelect1"></div>

    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>

    <script src="~/Content/vendor/animsition/js/animsition.min.js"></script>

    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/Content/vendor/select2/select2.min.js"></script>

    <script src="~/Content/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Content/vendor/daterangepicker/daterangepicker.js"></script>

    <script src="~/Content/vendor/countdowntime/countdowntime.js"></script>

    <script src="~/Content/js/main.js"></script>
</body>
</html>