WebBanQuanAo/Controllers/QuanLyNhapHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanQuanAo.Models;

namespace WebBanQuanAo.Controllers
{
    public class QuanLyNhapHangController : Controller
    {
        //
        BanQuanAoEntities2 db = new BanQuanAoEntities2();
        // GET: /QuanLyNhapHang/
        [HttpGet]
        public ActionResult NhapHang()
        {
           
            ViewBag.IdMLSP = db.MaLoaiSanPhams;
            ViewBag.ListSanPham = db.SanPhams;
            return View();
        }
        [HttpPost]
        public ActionResult NhapHang(PhieuNhap model,IEnumerable<ChiTietPhieuNhap> lstModel )
        {
          ViewBag.IdMLSP = db.MaLoaiSanPhams;
            ViewBag.ListSanPham = db.SanPhams;
            model.DaXoa = false;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();
            // save changes để lấy đc id phiếu nhập
            SanPham sanpham;
            foreach (var item in lstModel)
            {
                // cập nhật số lượng tồn
                sanpham = db.SanPhams.Single(n=> n.IdSanPham==item.IdSanPham);
                sanpham.SoLuongTon += item.SoLuongNhap;
                // gán mã phiếu nhập cho phiếu nhập
                item.IdPN = model.IdPN;
            }
            db.ChiTietPhieuNhaps.AddRange(lstModel);
            db.SaveChanges();
            return View();
        }
        [HttpGet]
        public ActionResult SanPhamHetHang()
        {
            // liệt kệ danh sách sản phẩm gần hết hàn
            var lstSanPham = db.SanPhams.Where(n => n.DaXoa == false && n.SoLuongTon <= 15);
            return View(lstSanPham);
        }
        // tạo view nhập hàng
        [HttpGet]
        public ActionResult NhapHangDon(int? IdSanPham)
        {
            ViewBag.IdMLSP = new SelectList(db.MaLoaiSanPhams.OrderByDescending(n=> n.TenLSP),"IdMLSP","TenLSP");
            if (IdSanPham == null)
            {
                 Response.StatusCode = 404;
                 return null;
            }
            SanPham sanpham = db.SanPhams.SingleOrDefault(n => n.IdSanPham==IdSanPham);
            if (IdSanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }
        [HttpPost]
        public ActionResult NhapHangDon(PhieuNhap model, ChiTietPhieuNhap ctpn)
        {
            ViewBag.IdMLSP = new SelectList(db.MaLoaiSanPhams.OrderByDescending(n=> n.TenLSP),"IdMLSP","TenLSP");
            model.DaXoa = false;
            model.NgayNhap = DateTime.Now;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();
            // save changes để lấy đc id phiếu nhập
            ctpn.IdPN = model.IdPN;
            // cập nhật tồn
            SanPham sanpham = db.SanPhams.Single(n => n.IdSanPham == ctpn.IdSanPham);
            sanpham.SoLuongTon += ctpn.SoLuongNhap;
            sanpham.DonGia = ctpn.DonGiaNhap;
            db.ChiTietPhieuNhaps.Add(ctpn);
            db.SaveChanges();
            return View(sanpham);
        }
        //Giải phóng biến cho vùng nhớ
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	
	}
}

WebBanQuanAo/Views/QuanLyNhapHang/NhapHang.cshtml
@using WebBanQuanAo.Models;
@model PhieuNhap
@{
    ViewBag.Title = "Nhập hàng";
    Layout = "~/Views/Layout/AdminQuanTri.cshtml";
}
@{
    IEnumerable<MaLoaiSanPham> lstMLSP = ViewBag.lstMLSP as IEnumerable<MaLoaiSanPham>;
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>

<h1 style="font-weight:bold;text-align:center">Quản Lý Nhập Hàng</h1>
<br />
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2">
                Nhà cung cấp :
            </div>
            <div class="col-md-5">
                @*Chọn nhà cung cấp*@
                <select class="IdMLSP" name="IdMLSP">

                    @foreach (var item in lstMLSP)
                    {
                        <option value="@item.IdMLSP">@item.TenLSP</option>
                    }

                </select>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <br />
    <div class="row">
        <div class="col-md-12">
            @*Ngày nhập*@
            <div class="col-md-2">
                Ngày nhập :
            </div>
            <div class="col-md-5">
                <input name="NgayNhap" type="text" id="datepicker" />
            </div>
        </div>
        <div class="clearfix">  </div>
    </div>
    <br /><br>

                    //phần chi tiết nhập hàng
                    <table class="table tblChiTietPhieuNhap table-bordered table-condensed">
                        @{IEnumerable<SanPham> ListSanPham = ViewBag.ListSanPham as IEnumerable<SanPham>;}
                        @*Tạo ra 1 tr với nội dung nhập hàng của 1 sản phẩm*@
                        <tr class="trNhapHang" style="display:none">
                            <td>
                                <select class="ddlSanPham" name="" style="">
                                    @foreach (var item in ListSanPham)
                                    {
                                        <option value="@item.IdSanPham">@item.TenSanPham</option>
                                    }
                                </select>
                            </td>
                            <td>
                                <input name="" class="txtDonGia" value="0" />
                            </td>
                            <td>
                                <input name="" class="txtSoLuong" value="0" />
                            </td>
                            <td>
                                <input name="" class="btnDelete btn btn-danger" value="-" style="width:30px;height:30px " />
                            </td>
                        </tr>
                        <tr class="trFirstChild" data-id="-1">
                            <td>Sản phẩm</td>
                            <td>Đơn giá nhập</td>
                            <td>Số lượng nhập</td>
                            <td></td>
                        </tr>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <input type="button" value="+" class="btn btn-success" id="btnAdd" style="padding:9px 12px" />
                            <input type="submit" value="Nhập hàng" class="btn btn-primary" id="btnNhapHang" style="padding:9px 12px" />
                        </div>
                    </div>
}
<script>
    $("#btnAdd").click(function () {
        //bước 4:
        var id_cuoi = $(".tblChiTietPhieuNhap").find("tr:last-child").attr("data-id");
        i = parseInt(id_cuoi) + 1;
        // bước 1: lấy nội dung thẻ tr
        var tdnoidung = $(".trNhapHang").html();
        // bước 2: tạo một td lấy nội dung
        var trnoidung = "<tr class =\"trNhapHangEd\" data-id =\"" + i + "\">" + tdnoidung + "</tr>";
        // bước 3: lấy thể tr apden vào table
        $(".tblChiTietPhieuNhap").append(trnoidung);
        loadIDLENTHE();
    });
    // hàm load id lên thẻ
    function loadIDLENTHE() {
        $(".trNhapHangEd").each(function () {
            // lấy data id của thẻ tr hiện tại
            var id = $(this).attr("data-id");
            var nameIdSanPham = "[" + id + "].IdSanPham"; // tạo mã sản phẩm
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap"; // tạo số lượng
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap"; // tạo đơn giá
            $(this).find(".ddlSanPham").attr("name", nameIdSanPham);
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);
        });
    }
    function CapNhatID() {
        // lấy lại tr
        var id_cuoi = $(".tblChiTietPhieuNhap").find("trFirstChild").attr("data-id");
        i = parseInt(id_cuoi) + 1;

        $(".trNhapHangEd").each(function () {
            // lấy data id của thẻ tr hiện tại
            var id = i;
            $(this).attr("data-id", i);
            // cập nhật lại id sau khi xóa
            var nameIdSanPham = "[" + id + "].IdSanPham"; // tạo mã sản phẩm
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap"; // tạo số lượng
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap"; // tạo đơn giá
            $(this).find(".ddlSanPham").attr("name", nameIdSanPham);
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);
            i++;
        });
    }

    // xử lý nhập hàng
    $("#btnNhapHang").click(function () {
        if (KiemTraDonGia() == false) {
            // nếu tồn tại một giá trị bất kì thuộc class đơn giá ko phải số thì ngăn ko cho submit về server
            return false;
        }
        if (KiemTraSoLuong() == false) {
            // nếu tồn tại một giá trị bất kì thuộc class đơn giá ko phải số thì ngăn ko cho submit về server
            return false;
        }
    });
    function KiemTraDonGia() {
        var bl = true;
        // duyệt vòng lặp each
        $(".txtDonGia").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Đơn giá không hợp lệ");
                bl = false;
                return bl;
            }
        });
        return bl;
    }
    function KiemTraSoLuong() {
        var bl = true;
        //Duyệt vòng lặp each
        $(".txtSoLuong").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Số lượng không hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }

    //xử lý xóa
    $("body").delegate(".btnDelete", "click", function () {
        // xóa phần tử cha thứ ngoài
        $(this).closest(".trNhapHangEd").remove();
        CapNhatID();
    });

</script>

WebBanQuanAo/Views/QuanLyNhapHang/NhapHangDon.cshtml
@using WebBanQuanAo.Models;

@model SanPham
@{
    ViewBag.Title = "Nhập hàng sản phẩm";
    Layout = "~/Views/Layout/AdminQuanTri.cshtml";
}

<legend>Nhập hàng cho sản phẩm <b style="color: rgb(192,0,0)">@Model.TenSanPham</b> </legend>
<div class="row">
    <div class="col-md-3">
        <div class="imgSP">
            <img style="height: 250px; width: 300px;" src="@Url.Content("~/Content/ckfinder/core/connector/aspx/" + Model.HinhAnh)" />
        </div>
    </div>
    <div class="col-md-9">
        <div class="ttSP">
            <h3>Mã loại sản phẩm: @Model.MaLoaiSanPham.TenLSP</h3>
            <h3>Loại sản phẩm: @Model.LoaiSanPham.TenLoai</h3>
            <h3>Số lượng tồn: @Model.SoLuongTon</h3>
            <h3>Đơn Giá: @Model.DonGia.Value.ToString("#,##")</h3>
        </div>
    </div>
</div>
<br />

@*thêm hình ảnh*@
<h2 style="font-size:20px; font-weight:bold;padding:10px;">Thông Tin Nhập Hàng</h2>
@using (Html.BeginForm("NhapHangDon", "QuanLyNhapHang"))
{
    <div class="form-horizontal">
        <hr />
        @Html.Hidden("IdSanPham", Model.IdSanPham)
        <div class="form-group">
            <label class="control-label col-md-2">Mã loại sản phẩm :</label>
            <div class="col-md-2">
                @{var lstMLSP = (SelectList)ViewBag.IdMLSP;}
                @Html.DropDownList("IdMLSP", lstMLSP, new { @class = "IdMLSP" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Đơn Giá :</label>
            <div class="col-md-10">
                @Html.TextBox("DonGiaNhap")
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Số Lượng Nhập :</label>
            <div class="col-md-10">
                @Html.TextBox("SoLuongNhap")
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nhập Hàng" class="btn btn-primary" />
            </div>
        </div>
    </div>

}

<style>
    .imgSP {
        border: 1px solid #999999;
        background-color: #fff;
   
        height: 250px;
        width: 300px;
    }
</style>

WebBanQuanAo/Views/QuanLyNhapHang/SanPhamHetHang.cshtml
@using WebBanQuanAo.Models;
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "sản phẩm hết hàng";
    Layout = "~/Views/Layout/AdminQuanTri.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}
<h1 style="font-weight:bold;text-align:center">Sản phẩm hết hàng</h1>
<br />

@grid.GetHtml(
            tableStyle: "table table-bordered table-condensed table-responsive",
            headerStyle: "gridHead",
            footerStyle: "gridHead",
            rowStyle: "gridRow",
            alternatingRowStyle: "gridAlter",
            columns: grid.Columns(
                        grid.Column("IdSanPham", "Mã sản phẩm"),
                        grid.Column("TenSanPham", "Tên sản phẩm"),
                         grid.Column("SoLuongTon", "Số Lượng Tồn"),
                      grid.Column("DonGia", "Đơn giá nhập"),
                        grid.Column("HinhAnh", "Hình ảnh", format: p => @Html.Raw("<img width=\"200\" height=\"250\" src = \"../Content/ckfinder/core/connector/aspx/" + p.HinhAnh + "\">")),
                        grid.Column("Nhập Hàng", format: p => @Html.ActionLink("Nhập Hàng", "NhapHangDon", new { @IdSanPham = p.IdSanPham }, new { @class = "btn btn-success", @target = "_blank" }))
                 ))